### ISSUE TITLE
Does not validate pattern properties correctly

### ISSUE THREAD

**Issue by davidarnold** [davishmcclurg/json_schemer#11]
# Problem

Per the JSON Schema validation spec, `pattern` properties should be evaluated per the "ECMA 262 regular expression dialect."

Of course, exact compliance is impossible, but Ruby's `Regexp` behavior for `^` and `$` makes `JSONSchemer` _very_ noncompliant.

## Failure 1
An externally published schema uses `^foo$`.  `JSONSchemer` will fail to reject multiline instances.

`JSONSchemer` erroneously accepts:
```
foo
foo
foo
```

## Failure 2
As a Ruby developer, I publish a schema that uses `\Afoo\z`.  Compliant JSON Schema implementations (say, running on an actual ECMA 262 engine) fail to accept _and_ fail to reject correctly.

ECMA 262 erroneously accepts:
`Afooz`

ECMA 262 erroneously rejects:
`foo`

# Solutions

Obviously, this is a tricky situation, so I am opening the issue mostly to start a discussion.

Ruby's quirky behavior is very well documented by now, and I have not seen anything that says you can turn off its multiline mode.

If I had to propose a solution, I would suggest either requiring a foreign regex library like https://github.com/mudge/re2, or gracefully upgrading to it when available.

To me this issue is fairly serious because faulty regex checking can and will produce security vulnerabilities.

**Comment by davishmcclurg** [comment]
Thanks for taking the time to open an issue. Here's my attempt at a fix: https://github.com/davishmcclurg/json_schemer/compare/ecma-262-anchors

It looks like there's at least one library (https://github.com/janosch-x/js_regex) for converting ruby regular expressions to javascript, but I couldn't find anything to do the opposite.

re2 looks interesting, but I'm concerned about losing jruby support.

**Comment by davidarnold** [comment]
Very clever solution.  I had not thought about jruby compatibility.

So to confirm with this change, if I am building a schema doc, I should use ECMA-style `^` `$` anchors and JSONSchemer will enforce them appropriately?

**Comment by davishmcclurg** [comment]
That's correct. That branch converts the ECMA-style anchors to their Ruby equivalents. Do you know of any other regex incompatibilities?

**Comment by davidarnold** [comment]
There are a ton of incompatibilities, but usually they are in the form of Ruby being a superset of ECMA 262.  ECMA 262 defines a very small grammar in [the spec](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1).

As an example, `\h` and `\H` define a hex digit character class in Ruby which is unknown by ECMA 262.  They would be treated as literal `h` and `H` respectively.

Short of finding an ECMA 262 compatible regex engine, there is probably not much you can do about it.  Theoretically, if [regexp_parser](https://github.com/ammar/regexp_parser) supported an ECMA 262 syntax module, you could do a parse tree transformation, but that is getting pretty crazy.

**Comment by davishmcclurg** [comment]
That's what I was afraid of. From what I can tell, that fix will bring regex support into line with the recommended subset of the syntax: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

**Comment by davidarnold** [comment]
I agree that if a regex written using only the recommended JSON Schema regex subset evaluates correctly in JSONSchemer, then the issue is resolved.  It would be tedious and potentially low value, but unit tests could be written to verify compatibility with the documented subset.

The practical possibility of encountering a problematic regex is pretty low considering that most services would probably only consume their own schemas.  In fact, consuming a foreign regex from an untrustworthy source is always a bad idea anyway due to things like accidental or malicious [catastrophic backtracking](http://www.rexegg.com/regex-explosive-quantifiers.html).  (side note: I found out about Google's RE2 as being an engine supposedly immune to those hidden bombs)

The issue I am documenting here, however, made it impossible to publish a schema that worked correctly for both your clients and your Ruby service.  This fix resolves that.

**Comment by davishmcclurg** [comment]
That makes sense. I hadn't thought about the client/server issue. Thanks for all the detail.

I just merged the fix and release a new version.
