### ISSUE TITLE
Add support for Draft 2020-12

### ISSUE THREAD

**Issue by heynan0** [davishmcclurg/json_schemer#116]
## Specification

http://json-schema.org/specification-links.html#2020-12

## Identifier

```
{ "$schema": "https://json-schema.org/draft/2020-12/schema" }
```

Reference (based on this): 

> The identifier for Draft 2019-09 is https://json-schema.org/draft/2019-09/schema.

https://json-schema.org/understanding-json-schema/reference/schema.html#id4

**Comment by davishmcclurg** [comment]
Released in 2.0.0. Draft 2020-12 is now the default draft.
