### ISSUE TITLE
Can the gem put some short and readable validation result?

### ISSUE THREAD

**Issue by yvesll** [davishmcclurg/json_schemer#120]
The validate API returns an enumerable object which contains very detailed validation information. However, sometimes the user want to get short description of them, a typical scenario is the CLI, abundant hash object displayed in the terminal may make users confused.
The gem `ruby-json-schema` just print a more readable message like:
```shell
=> "The property '#/a' of type String did not match the following type: integer"
```

So it would be feasible that json_schemer can add an option or wrap API to put a more readable validation error message.

**Comment by ahx** [comment]
@yvesll This seems be related to https://github.com/davishmcclurg/json_schemer/issues/27. I think we should go with the default output formatting and close this.

**Comment by davishmcclurg** [comment]
There's also `JSONSchemer::Errors.pretty` which will convert an error hash to a string like you're describing. Does that cover your use case?

**Comment by yvesll** [comment]
Thanks, @davishmcclurg, @ahx, it covers my case and it would be feasible to add some documents for it.

**Comment by davishmcclurg** [comment]
Ok, thanks @yvesll.
