### ISSUE TITLE
Parse and resolve schema `$ref`s w/out validating

### ISSUE THREAD

**Issue by neilpa** [davishmcclurg/json_schemer#136]
Is it possible to get the fully resolved schema with all the `$ref`s replaced with the actual definitions (assuming no recursion). I've got some fairly complex schemas spread across a few dozen local files that get rolled into one schema that I'd like to get a unified view of. I've been digging into the code and AFAICT the only time `$ref`s get resolved is during validation.

**Comment by davishmcclurg** [comment]
Hi @neilpa—that's not currently possible, but I'd like to add it as a feature after [2.0.0](https://github.com/davishmcclurg/json_schemer/pull/135) is released.

It looks like the spec calls the generated schemas [compound documents](https://json-schema.org/draft/2020-12/json-schema-core.html#section-9.3) and the resolution process [bundling](https://json-schema.org/draft/2020-12/json-schema-core.html#section-9.3.1).

**Comment by neilpa-inv** [comment]
Thanks for the links. I was able to easily hack something together that pre-processes the `$ref` values and inlines the remote schemas or local `$defs` before handing it off to JSONSchemer. Definitely not robust, but we already have a custom `ref_resolver` so I was able to leverage that.

**Comment by unicornzero** [comment]
I'm also interested in pre-validation ref resolution, but haven't dug into that yet. (Too many things to research, too little time!) @neilpa-inv I'd be curious to see what you hacked together as a starting point, if you don't mind sharing.

**Comment by neilpa-inv** [comment]
@unicornzero Unfortunately I can't share the actual code. Roughly speaking, it looks like this with the replacement step omitted since that depends on the various `$ref`s you need to handle. (I'm also very much not a Ruby person so there may be a more idiomatic way to do this).

```rb
q = [ JSON.parse("path/to/root/schema.json") ]
while !q.empty?
  obj = q.shift
  if obj.is_a? Hash
    if obj.key? "$ref"
      ref = obj["$ref"]
      obj.delete_if { true }
      # add values to `obj` from the the resolved remote $ref or local $def
      q.unshift(obj)
    else
      q.concat(obj.values)
    end
  elsif obj.is_a? Array
    q.concat(obj)
  end
end
```

**Comment by unicornzero** [comment]
Thanks for sharing what works for you! I'll refer back to this when I'm next digging into this part of things.

**Comment by davishmcclurg** [comment]
I added bundling support to the [next branch](https://github.com/davishmcclurg/json_schemer/tree/next) for release in [2.0.0](https://github.com/davishmcclurg/json_schemer/pull/135). If you want to try it out, it currently works like this:

```ruby
schema = {
  '$id' => 'http://example.com/schema',
  'allOf' => [
    { '$ref' => 'schema/one' },
    { '$ref' => 'schema/two' }
  ]
}
refs = {
  URI('http://example.com/schema/one') => {
    'type' => 'integer'
  },
  URI('http://example.com/schema/two') => {
    'minimum' => 11
  }
}
schemer = JSONSchemer.schema(schema, :ref_resolver => refs.to_proc)

schemer.bundle
# => {"$id"=>"http://example.com/schema",
#     "allOf"=>[{"$ref"=>"schema/one"}, {"$ref"=>"schema/two"}],
#     "$schema"=>"https://json-schema.org/draft/2020-12/schema",
#     "$defs"=>
#      {"http://example.com/schema/one"=>{"type"=>"integer", "$id"=>"http://example.com/schema/one", "$schema"=>"https://json-schema.org/draft/2020-12/schema"},
#       "http://example.com/schema/two"=>{"minimum"=>11, "$id"=>"http://example.com/schema/two", "$schema"=>"https://json-schema.org/draft/2020-12/schema"}}}
```
