### ISSUE TITLE
Introduce optional callbacks for validating non-built-in contentType, contentEncoding, format

### ISSUE THREAD

**Issue by ekzobrain** [davishmcclurg/json_schemer#137]
Currently if a format/contentType/contentEncoding is not handled natively - exception is thrown and processing finishes. This makes those features unusable as built-in values support is limited.
Suggestion:
1. List built-in supported format/contentType/contentEncoding in docs
2. Introduce optional callbacks to handle any custom values. If a callback is provided - exception is not thrown.
3. Point out in exception messages that optional callbacks may be passed to handle unsupported value

**Comment by davishmcclurg** [comment]
I just opened a PR covering this: https://github.com/davishmcclurg/json_schemer/pull/148
Let me know if you can try it out—thanks!

**Comment by ekzobrain** [comment]
Thanks, I'll check it soon

**Comment by davishmcclurg** [comment]
@ekzobrain have you had a chance to try out that branch? I'd like to make a release this week and I'm hoping to get it in

**Comment by davishmcclurg** [comment]
@ekzobrain I merged that PR into 2.1.0 and will release in the next few days: https://github.com/davishmcclurg/json_schemer/pull/156
Let me know if you still plan to try it out.

**Comment by ekzobrain** [comment]
@davishmcclurg  I've done some tests and it looks quite good. I am just unsure about the consistency of current behavior:
When validator meets an unknown format value (and no callback is registered to handle it) - it is just ignored and validation passes
But for unknown contentMediaType an exception is raised.

May be it's time to become more strict and raise an UnknownFormat exception as well? may be introduce this with a new configuration option set to `false` until 3.0.

**Comment by ekzobrain** [comment]
Or another way is to handle unknown contentMediaType/contentMediaEncoding the same way as format keyword - just ignore if it's value is unknown.

**Comment by davishmcclurg** [comment]
> When validator meets an unknown format value (and no callback is registered to handle it) - it is just ignored and validation passes
> But for unknown contentMediaType an exception is raised.

The [spec](https://json-schema.org/draft/2020-12/json-schema-validation#section-7.2.3) is more specific about unknown formats:

> An implementation MUST NOT fail to collect unknown formats as annotations. When the Format-Assertion vocabulary is specified, implementations MUST fail upon encountering unknown formats.

Which I think means unknown formats shouldn't fail unless the Format-Assertion vocabulary is specified. Currently it's possible to change how unknown formats are handled by switching between the Format-Annotation and Format-Assertion vocabularies:

```
?> meta_schemas = {
?>   URI('https://example.com/assertion') => {
?>      '$vocabulary' => {
?>        'https://json-schema.org/draft/2020-12/vocab/core' => true,
?>        'https://json-schema.org/draft/2020-12/vocab/format-assertion' => true
?>      }
?>   },
?>   URI('https://example.com/annotation') => {
?>      '$vocabulary' => {
?>        'https://json-schema.org/draft/2020-12/vocab/core' => true,
?>        'https://json-schema.org/draft/2020-12/vocab/format-annotation' => true
?>      }
?>   }
>> }
=>
{#<URI::HTTPS https://example.com/assertion>=>{"$vocabulary"=>{"https://json-schema.org/draft/2020-12/vocab/core"=>true, "https://json-schema.org/draft/2020-12/vocab/format-assertion"=>true}},
...

?> JSONSchemer.schema(
?>   {
?>     '$schema' => 'https://example.com/assertion',
?>     'format' => 'unknown',
?>   },
?>   :ref_resolver => meta_schemas.to_proc
>> ).valid?('1')
/Users/dharsha/repos/json_schemer/lib/json_schemer/draft202012/vocab/format_assertion.rb:12:in `block in parse': unknown (JSONSchemer::UnknownFormat)

?> JSONSchemer.schema(
?>   {
?>     '$schema' => 'https://example.com/annotation',
?>     'format' => 'unknown',
?>   },
?>   :ref_resolver => meta_schemas.to_proc
>> ).valid?('1')
=> true
```

`contentEncoding` and `contentMediaType` may be confusing because they behave like an assertion vocabulary instead of an annotation one. I think this matches the existing behavior, but it may make sense to introduce something like a Content-Annotation vocabulary in the future that ignores unknown values.

**Comment by ekzobrain** [comment]
Ok, it's reasonable...
