### ISSUE TITLE
Include JSONSchemaTestSuite as git submodule

### ISSUE THREAD

**Issue by ekzobrain** [davishmcclurg/json_schemer#138]
Remove it from project source and include as git submodule. There's no need to store a copy while it can be included upon request by anyone willing to run tests

**Comment by davishmcclurg** [comment]
It actually used to be a submodule: https://github.com/davishmcclurg/json_schemer/commit/ed6ba60caa2bd1fe1be72e8b189bd41bcc269b12
but I switched to subtree: https://github.com/davishmcclurg/json_schemer/commit/359b1a5596fbf1472409ce4f869ae23772e782f5

I haven't had much trouble using it as a subtree. Is there any particular reason you'd like it to be a submodule? Unfortunately, I can't remember why I thought submodule was annoying.

**Comment by ekzobrain** [comment]
Ah, if you met any troubles managing submodule than OK. It's not very important, but including test suites and scenarios as submodule is a common practice to lighten the primary codebase, because test are actually not needed when installing library.

**Comment by davishmcclurg** [comment]
Ok, thanks for opening the issue. I'll leave it as a subtree for now. For what it's worth, the test suite files shouldn't be included when installing the gem (just when cloning the repo).
