### ISSUE TITLE
URI.unescape is obsolete

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [davishmcclurg/json_schemer#14]
Lots of such warnings are printed in the console:
```
json_schemer-0.1.7/lib/json_schemer/schema/base.rb:231:in `validate_ref': warning: URI.unescape is obsolete
```

This issue has plagued any ruby library that more or less deals with URIs for the last few years and while the replacement is a case-by-case thing, I believe a common way to handle this is to just rely on Addressable.
Just an idea but how about replacing uri_template, which has [not been updated in 4 years](https://rubygems.org/gems/uri_template), by Addressable and kill two birds with one stone?

For reference, here's the original deprecation "bug" https://bugs.ruby-lang.org/issues/4167

**Comment by davishmcclurg** [comment]
Hi @jfeltesse-mdsol, thanks for opening the issue. I tried Addressable when I was first writing this, but it seemed to be pretty forgiving with invalid templates. I couldn't get it to throw an error:

```
> Addressable::Template.new('http://example.com/dictionary/{term:1}/{term')
=> #<Addressable::Template:0x3fe583585428 PATTERN:http://example.com/dictionary/{term:1}/{term>
```

Any ideas?

**Comment by jfeltesse-mdsol** [comment]
I guess it's a matter of interpretation, it looks like the choice that was made by Addressable is to not try to outsmart the user and consider anything that's not properly formatted as a template variable to be just another part of the URI.

```ruby
tmpl = Addressable::Template.new('http://example.com/dictionary/{term:1}/{term')
# => #<Addressable::Template:0x3fd984dc434c PATTERN:http://example.com/dictionary/{term:1}/{term>
tmpl.variables
# => ["term"]
```

To begin with, would that example URI be valid in json schema?

My initial issue is just about warnings being emitted so this is super low priority, feel free to close and move on. I can foresee the same issue reported times and times again though.

**Comment by jfeltesse-mdsol** [comment]
I see... 

I'm not sure how to best resolve this. 
json_schemer could have its own invalid templated URI detection but that's opening a new can of worms just to solve some warnings... 🤔 

Closing for now!

**Comment by davishmcclurg** [comment]
Should be fixed: https://github.com/davishmcclurg/json_schemer/pull/16
