### ISSUE TITLE
Validation of date-time

### ISSUE THREAD

**Issue by pboling** [davishmcclurg/json_schemer#153]
`2010-01-01T12:00:00,1Z` is a valid [ISO-8601](https://ijmacd.github.io/rfc3339-iso8601/), but not RFC-3339, which is what JSONSchema claims to require.

High chance I've missed something though.

**Comment by davishmcclurg** [comment]
It looks like it's currently invalid:

```
>> JSONSchemer.schema({ 'format' => 'date-time' }).valid?('2010-01-01T12:00:00,1Z')
=> false
```

I think that's correct. Are you expecting it to be valid?

**Comment by davishmcclurg** [comment]
Thanks for pointing me to [that site](https://ijmacd.github.io/rfc3339-iso8601/)—it's helpful. I added [some tests](https://github.com/davishmcclurg/json_schemer/commit/daf4fce5086a1515c5882f10371f280d6eae2fb0) using the generated examples and realized a couple edge cases aren't supporting space separators for `date-time`.

**Comment by pboling** [comment]
I'll have to revisit, and see what I was doing to get that date string as valid.  I may have just flipped the expectation around in my head. 😬 Late night coding problems.

**Comment by pboling** [comment]
Closing this, as there's nothing further to be done here.
