### ISSUE TITLE
Best way to handle 'nil' values as 'null' in json schema

### ISSUE THREAD

**Issue by Austio** [davishmcclurg/json_schemer#154]
Hello, thank you for the awesome library.

I am using this library to validate some events that are Ruby objects.

What would be the best way to handle treating ruby 'nil' values as 'null'.  [There is an example here is in json-schema](https://github.com/voxpupuli/json-schema/blob/2cc181bfd38c2abe8914b02ced21d9ebdf1f6e77/lib/json-schema/attributes/enum.rb#L12) for a reference.

Thanks again!

**Comment by davishmcclurg** [comment]
Hi @Austio. I'm not sure exactly what you mean here. `nil` should already be treated as `null`:

```
>> JSONSchemer.schema({ 'type' => 'null' }).valid?(nil)
=> true
>> JSONSchemer.schema({ 'type' => 'null' }).valid?(1)
=> false
```

Or do you mean something else?

**Comment by Austio** [comment]
@davishmcclurg my mistake here, you are 100% right, i misinterpreted the error.

:tophat: for the code to validate and thanks again for your work on this library and help on issues.
