### ISSUE TITLE
`JSONSchemer` is confused about string or symbol keys

### ISSUE THREAD

**Issue by exterm** [davishmcclurg/json_schemer#166]
On version `2.1.1`:

```ruby
data = { "baz": 1 }
schema = JSONSchemer.schema({ "type": "object", "properties": { "foo": { "default": "bar" } } }, insert_property_defaults: true)
schema.validate(data)
data

# => {:baz=>1, "foo"=>"bar"}
```

IMO this should either result in only symbol keys or only string keys.

**Comment by exterm** [comment]
I can work around this by using `data.with_indifferent_access` but it's not great.

**Comment by davishmcclurg** [comment]
> IMO this should either result in only symbol keys or only string keys.

How would you determine what type of key to use if there are no existing keys? In your example, if `:baz` wasn't present, would it still insert a symbol?

Another way I could imagine addressing this is something like `insert_property_defaults: :symbol` to specify which type of key you want.

**Comment by exterm** [comment]
> How would you determine what type of key to use if there are no existing keys?

I think I'd prefer JSONSchemer to decide for one key type to use and convert the other type to it, always. Do you see any reasons not to do that?

**Comment by davishmcclurg** [comment]
Do you mean convert the keys in place? I think it would be confusing to modify the input hash like that (ie, changing all the key types) during validation.

**Comment by exterm** [comment]
Ah. I agree.

The problem here is that "Ruby representation of JSON" is so ambiguous. It would be great to have some kind of JSONData type that removed that inconsistency, but I believe that to be out of scope for this gem.

**Comment by davishmcclurg** [comment]
> The problem here is that "Ruby representation of JSON" is so ambiguous. It would be great to have some kind of JSONData type that removed that inconsistency, but I believe that to be out of scope for this gem.

Yeah, I agree the ambiguity is annoying. I'd like to see it solved in Ruby itself, but it seems unlikely at this point. Somewhat related:

- https://bugs.ruby-lang.org/issues/5964
- https://bugs.ruby-lang.org/issues/7792
- https://bugs.ruby-lang.org/issues/11882
- https://bugs.ruby-lang.org/issues/17472

Would the `insert_property_defaults: :symbol` option be helpful in your case? I'm still considering adding it.

**Comment by exterm** [comment]
Yes I think it would improve the situation, although I'm no longer working on that code so can't play around with it to be sure.
