### ISSUE TITLE
$id of invalid type throws an exception

### ISSUE THREAD

**Issue by ekzobrain** [davishmcclurg/json_schemer#174]
```ruby
schemer = JSONSchemer.schema({ "$id" => 1 })
schemer.valid_schema?
```
throws an exception "bad argument (expected URI object or URI string) (ArgumentError)". Shouldn't it return a validation error instead of an unhandled exception?

**Comment by davishmcclurg** [comment]
> throws an exception "bad argument (expected URI object or URI string) (ArgumentError)". Shouldn't it return a validation error instead of an unhandled exception?

Yep, you're right. I'm going to close this because I think it's covered by: https://github.com/davishmcclurg/json_schemer/issues/167

I've got a fix in the works.
