### ISSUE TITLE
Validation succeeds when none of the object properties exist

### ISSUE THREAD

**Issue by natebrunette** [davishmcclurg/json_schemer#187]
I created the start of a PR here to demonstrate the issue: https://github.com/davishmcclurg/json_schemer/pull/186

If the object you're trying to validate doesn't contain any of the fields in the schema, it will pass as valid.

I dug into it a bit, but couldn't figure out a way to fix it without breaking other things. I also didn't see anything in the configuration that would work in this case. It might be nice to have some sort of strict setting that would fail if the data differed from the schema in any way. It's possible the library is already supposed to work that way and this edge case just needs to be handled.

**Comment by davishmcclurg** [comment]
This is actually the correct behavior for `properties`: https://json-schema.org/draft/2020-12/json-schema-core#section-10.3.2

> Validation succeeds if, for each name that appears in both the instance and as a name within this keyword's value, the child instance for that name successfully validates against the corresponding schema.

You'll need a combination of `additionalProperties` and `required` if you want to restrict the data to what's present in the schema.

**Comment by natebrunette** [comment]
Thanks, after adding required properties it seems to be working!
