### ISSUE TITLE
Test that passes with json_schemer 1.0.0 fails with json_schemer 2.0.0

### ISSUE THREAD

**Issue by denisahearn** [davishmcclurg/json_schemer#190]
After upgrading our Rails application from `json_schemer 1.0.0` to `2.0.0`, we found that a test that verified that `JSONSchemer.schema(schema).validate(value).to_a` was working as expected for one of our JSON schemas stopped working.

Specifically, we are using the following JSON schema to verify geospatial bounding boxes consisting of an array of 4 numeric values with specific minimums and maximums defined for each of the 4 elements:

```
{
  "title": "A bounding box in the form [west, south, east, north]",
  "type": "array",
  "minItems": 4,
  "maxItems": 4,
  "items": [
    {
      "title": "West (Minimum Longitude)",
      "type": "number",
      "minimum": -360.0,
      "maximum": 360.0
    },
    {
      "title": "South (Minimum Latitude)",
      "type": "number",
      "minimum": -90.0,
      "maximum": 90.0
    },
    {
      "title": "East (Maximum Longitude)",
      "type": "number",
      "minimum": -360.0,
      "maximum": 360.0
    },
    {
      "title": "North (Maximum Latitude)",
      "type": "number",
      "minimum": -90.0,
      "maximum": 90.0
    }
  ]
}
```

The following two Rails tests pass when using version `json_schemer 1.0.0`, however after upgrading to `json_schemer 2.0.0` the second test breaks:

```
test "valid bbox" do
  bbox = [0, 0, 1, 1] # valid bbox
  errors = JSONSchemer.schema(BBOX_SCHEMA).validate(bbox).to_a
  assert errors.empty?
end

test "invalid bbox" do
  bbox = [361, 0, 1, 1] # west longitude exceeds maximum longitude
  errors = JSONSchemer.schema(BBOX_SCHEMA).validate(bbox).to_a
  assert errors.any?
end
```

Attached is a sample Rails application that demonstrates this issue. The `Gemfile` in the app defines specific versions of `json_schemer` to use. Modify this file to switch between `1.0.0` and `2.0.0`. Then run the following command to see the issue:

```
rails test test/bbox_schema_test.rb
```

[json_schemer_test.zip](https://github.com/user-attachments/files/16127545/json_schemer_test.zip)

I read through the [breaking changes](https://github.com/davishmcclurg/json_schemer/blob/main/CHANGELOG.md#200---2023-08-20) for version 2.0.0 but didn't find anything that specifically explained the difference in behavior between the two versions. Could this perhaps be a difference between the default meta schema used by `1.0.0` and the one used by `2.0.0`?

**Comment by davishmcclurg** [comment]
> Could this perhaps be a difference between the default meta schema used by `1.0.0` and the one used by `2.0.0`?

Yeah I think that's your problem. The default meta schema changed to draft 2020-12. Here's an explanation: https://json-schema.org/draft/2020-12/release-notes#changes-to-items-and-additionalitems

You can use an older draft by setting `$schema` in your schema, ie:

```
require "json_schemer"

schema = {
  "title": "A bounding box in the form [west, south, east, north]",
  "type": "array",
  "minItems": 4,
  "maxItems": 4,
  "items": [
    {
      "title": "West (Minimum Longitude)",
      "type": "number",
      "minimum": -360.0,
      "maximum": 360.0
    },
    {
      "title": "South (Minimum Latitude)",
      "type": "number",
      "minimum": -90.0,
      "maximum": 90.0
    },
    {
      "title": "East (Maximum Longitude)",
      "type": "number",
      "minimum": -360.0,
      "maximum": 360.0
    },
    {
      "title": "North (Maximum Latitude)",
      "type": "number",
      "minimum": -90.0,
      "maximum": 90.0
    }
  ]
}

valid_bbox = [0, 0, 1, 1]
invalid_bbox = [361, 0, 1, 1]

puts JSONSchemer.schema(schema).valid?(valid_bbox)
# true
puts JSONSchemer.schema(schema).valid?(invalid_bbox)
# true

schema.merge!("$schema": "http://json-schema.org/draft-07/schema#")

puts JSONSchemer.schema(schema).valid?(valid_bbox)
# true
puts JSONSchemer.schema(schema).valid?(invalid_bbox)
# false
```

**Comment by denisahearn** [comment]
@davishmcclurg Specifying `"$schema": "http://json-schema.org/draft-07/schema#"` in our JSON schema fixed the issue for us, and we're now using the latest version of this gem. Thanks!
