### ISSUE TITLE
Attempting to validate an Inline `oneOf` union with a `discriminator` raises `key not found: "$ref"` error

### ISSUE THREAD

**Issue by moberegger** [davishmcclurg/json_schemer#192]
Given a specification like

```ruby
openapi = {
  'openapi' => '3.0.1',
  'components' => {
    'schemas' => {
      'Pets' => {
        'oneOf' => [
          {
            'type' => 'object',
            'properties' => {
              'id' => {
                'type' => 'integer',
              },
              'petType' => {
                'type' => 'string',
                'enum' => ['cat'],
              },
              'meow' => {
                'type' => 'string',
              },
            },
          },
          {
            'type' => 'object',
            'properties' => {
              'id' => {
                'type' => 'integer',
              },
              'petType' => {
                'type' => 'string',
                'enum' => ['dog'],
              },
              'bark' => {
                'type' => 'string',
              },
            },
          },
        ],
        'discriminator' => {
          'propertyName' => 'petType',
        },
      },
    },
  },
}
```

and then attempting to validate an input (which can either be valid or invalid)

```ruby
schemer = JSONSchemer.openapi(openapi).schema('Pet')
schemer.valid_schema? # returns true
schemer.valid?({ "id": 1, "petType": "cat", "meow": "Prrr" }) # Error
```

An error is thrown: `key not found: "$ref"`. 

If I omit the `discriminator` property from `Pet`, everything works as expected. So inline unions work in the absence of `discriminator`, but do not work when provided.

Poked around source a bit, and from what I can gather, the presence of the `discriminator` property [tells `json_schemer`](https://github.com/davishmcclurg/json_schemer/blob/main/lib/json_schemer/openapi31/vocab/base.rb#L30-L34) to validate unions differently, where it will only [look for the `$refs`](https://github.com/davishmcclurg/json_schemer/blob/main/lib/json_schemer/openapi31/vocab/base.rb#L59) when finding the subschemas.

I don't know if this is the expected behaviour or not; not sure if Openapi specifies whether or not `$ref`s _must_ be used when defining tagged unions. Looking at the [spec docs](https://spec.openapis.org/oas/v3.0.1#schema-object), I see: 
> oneOf - Inline or referenced schema MUST be of a [Schema Object](https://spec.openapis.org/oas/v3.0.1#schema-object) and not a standard JSON Schema.

Which seems to suggest that they can either be inline or references, as long as they are a valid schema object.

**Comment by ahx** [comment]
The [OAS says ](https://spec.openapis.org/oas/v3.1.0#discriminator-object): "When using the discriminator, inline schemas will not be considered."

This means that the example (without the `$refs`), should not work. 
I [have also asked in the OAS Slack channel](https://open-api.slack.com/archives/C1137F8HF/p1722515862881279) about this and it was [confirmed](https://open-api.slack.com/archives/C1137F8HF/p1722522240755909?thread_ts=1722515862.881279&cid=C1137F8HF) that it should not work with inline-schemas:

> oneOf entries need to be $refs to entries in the Components Object, because discriminator locates the schemas based on component names.  If you use mapping with all explicit URIs, then you can technically use inline schemas, although that's not very clear from the text and tools may or may not handle it correctly.

**Comment by davishmcclurg** [comment]
@moberegger `discriminator` is meant to pick a schema based on its name (in `#/components`) or by full URI. For simplicity, I decided not to consider inline schema URIs (spec: "When using the discriminator, inline schemas will not be considered."), but in your example it wouldn't make a difference. From what I can tell, your example doesn't need `discriminator` at all, because only one of your `oneOf` schemas will match based on `petType`. Is there another reason you're trying to use `discriminator` here?

> This means that the example (without the `$refs`), should not work. I [have also asked in the OAS Slack channel](https://open-api.slack.com/archives/C1137F8HF/p1722515862881279) about this and it was [confirmed](https://open-api.slack.com/archives/C1137F8HF/p1722522240755909?thread_ts=1722515862.881279&cid=C1137F8HF) that it should not work with inline-schemas:
> 
> > oneOf entries need to be $refs to entries in the Components Object, because discriminator locates the schemas based on component names.  If you use mapping with all explicit URIs, then you can technically use inline schemas, although that's not very clear from the text and tools may or may not handle it correctly.

Thanks for looking into this, @ahx! I did consider looking through inline schemas—unfortunately I can't remember why I avoided it.
