### ISSUE TITLE
`format.rb` throws an error if anything other than a string is passed to it

### ISSUE THREAD

**Issue by aaronFranssell** [davishmcclurg/json_schemer#2]
Hello,

I was experimenting with your gem when I noticed an issue. It appears that any when a schema specifying a `format` is passed a non-string value, then it will throw an exception. Code to repeat:
```
require 'json_schemer'
schema = {"format"=>"email" }
data = []
JSONSchemer.schema(schema).validate(data)
```

I will create a PR to address it. Let me know if you can merge the fix and push it out?

Thank you!

P. S. it looks like the test suite has not been pushed up. Getting:
```fatal: reference is not a tree: 2146b02555b163da40ae98e60bf36b2c2f8d4bd0
Unable to checkout '2146b02555b163da40ae98e60bf36b2c2f8d4bd0' in submodule path 'JSON-Schema-Test-Suite'
```

**Comment by davishmcclurg** [comment]
@aaronFranssell I just opened a PR that should address this issue: https://github.com/davishmcclurg/json_schemer/pull/4

Take a look and let me know if you see any issues with the approach.

**Comment by aaronFranssell** [comment]
@davishmcclurg Looks good! Thank you for taking care of this!

**Comment by davishmcclurg** [comment]
Pushed 0.1.5 to fix this issue
