### ISSUE TITLE
"value at ... is not a string" on YAML Date format:date fields

### ISSUE THREAD

**Issue by ulidtko** [davishmcclurg/json_schemer#203]
Hi @davishmcclurg !

I'm trying to validate existing yaml data against an existing schema (fixing the schema along the way, in another project).

Stumbling over this:

```ruby
>> data = YAML.load("field: 2024-12-26", permitted_classes: [Date])
=> {"field"=>#<Date: 2024-12-26 ((2460671j,0s,0n),+0s,-Infj)>}

>> JSONSchemer.schema({'type' => 'object', 'properties': {'field': {'type' => 'string', 'format' => 'date'} }}).validate(data).to_a
=> 
[{"data"=>#<Date: 2024-12-26 ((2460671j,0s,0n),+0s,-Infj)>,                                                                                                                                 
  "data_pointer"=>"/field",                                                                                                                                                                 
  "schema"=>{"type"=>"string", "format"=>"date"},                                                                                                                                           
  "schema_pointer"=>"/properties/field",                                                                                                                                                    
  "root_schema"=>{"type"=>"object", "properties"=>{"field"=>{"type"=>"string", "format"=>"date"}}},                                                                                         
  "type"=>"string",                                                                                                                                                                         
  "error"=>"value at `/field` is not a string"}]   
```

... okay, I understand, an instance of `Date` is indeed not a string, from JSONSchemer PoV.

However, without the `permitted_classes: [Date]` the yaml simply refuses to parse:
```ruby
>> data = YAML.load("field: 2024-12-26", permitted_classes: [])
/usr/lib/ruby/3.2.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
        from /usr/lib/ruby/3.2.0/psych/class_loader.rb:28:in `load'                                                                                                                         
        from (eval):2:in `date'                                                                                                                                                             
        from /usr/lib/ruby/3.2.0/psych/scalar_scanner.rb:66:in `tokenize'                                                                                                                   
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:65:in `deserialize'                                                                                                              
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:130:in `visit_Psych_Nodes_Scalar'
        from /usr/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /usr/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from /usr/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /usr/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /usr/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        ... 10 levels...
```

Apologies if you think it's out-of-scope for json_schemer to support this, or if I'm missing something obvious. Ruby isn't my daily driver...

This seems to be related https://github.com/ruby/psych/issues/489 — and it mentions `YAML.unsafe_load` which however exhibits the same issue anyway. I.e. parses to `Date`, causing `... is not a string` validation error.

I can't get `YAML.safe_load` to leave date-like-looking values alone, as strings. Any hints to achieve that?

Conceivably, `json_schemer` could also support `Date` objects in date validation. Please consider.

**Comment by ulidtko** [comment]
... monkeypatch workaround :unamused: 

```ruby
# See https://github.com/davishmcclurg/json_schemer/issues/203
class UnparsedDateMonkeyPatch
  def strptime strscalar, fmt, calendar
    strscalar #-- return input untouched, don't parse nothing.
  end
end
module YAML
  class ClassLoader
    class Restricted
      def find klassname
        return UnparsedDateMonkeyPatch.new if klassname == 'Date'
        super
      end
    end
  end
end
```

Horrible! I wish I didn't have to write this.

**Comment by davishmcclurg** [comment]
```

**Comment by davishmcclurg** [comment]
Hi @ulidtko. I don't the `YAML` library very well. It looks like if you put quotes around the date it parses it as a string:

```
>> YAML.load("field: '2024-12-26'")
=> {"field"=>"2024-12-26"}
```

> Conceivably, `json_schemer` could also support `Date` objects in date validation. Please consider.

At this point, I think this is beyond the scope of `json_schemer`.

**Comment by ulidtko** [comment]
Understood @davishmcclurg.

Quoting the dates is unfortunately not an option in my case — there're ~350 git-tracked data files (large-ish jekyll frontmatters) — with [the project's style guide](https://endoflife.date/contribute#new-adding-a-new-product) being explicit about keeping dates unquoted:

```yaml
    # Latest release date (optional).
    # Use valid dates, and do not add quotes around dates.
    latestReleaseDate: 2022-01-23
```

Even if I could change this now — it'd be a massive stop-the-world conflicts-everywhere PR changing around *46 thousand lines*. Not really viable... especially when justified by a bug between Ruby's yaml library and schema validator.

I guess, monkey-patch be it.

**Comment by davishmcclurg** [comment]
Another option would be to convert the dates back to strings after yaml parsing

**Comment by ulidtko** [comment]
The problem with that is: validation errors are shifting, to some other logic besides the `.validate()` call on schema.

I.e. invalid dates in the input now demand writing bespoke logic to traverse the yaml, catch exceptions, translate the error format, etc — despite the schema declaring `{"type": "string", "format": "date"}`.

Kind of defeats the purpose.

**Comment by ulidtko** [comment]
Hmmmm :thinking: 

Wonderfully, exact same issue has happened to `ajv`, a validator in JavaScript. https://github.com/ajv-validator/ajv-cli/issues/122

It comes from an "impedance mismatch" between JSON and YAML. One has a native `date` type (distinct from string!), the other hasn't.

The YAML spec does provision a nice solution to this (things called `CORE_SCHEMA` and `JSON_SCHEMA`, those intentionally omit the `date` type tag) — but it's indeed a concern for yaml parser libraries, rather than json-schema validators.

So you're right @davishmcclurg, it's out of scope here. I'll transfer the discussion elsewhere. Thanks for your responses!
