### ISSUE TITLE
Feature: Support for the OpenAPI variation of JSON Schema

### ISSUE THREAD

**Issue by DavidMikeSimon** [davishmcclurg/json_schemer#22]
The OpenAPI specification contains [a slightly modified subset of JSON Schema](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject). It would be handy for my use case if I could validate documents against it.

I'm interested in implementing this, would that be acceptable to integrate into this project? Any advice on how to approach it?

**Comment by davishmcclurg** [comment]
Hi @DavidMikeSimon—thanks for the interest!

I'd definitely be open to adding OpenAPI support. Right now the supported schemas are implemented here: https://github.com/davishmcclurg/json_schemer/tree/master/lib/json_schemer/schema and are subclasses of `JSONSchemer::Schema::Base`. So I think adding another version there would be the place to start.
