### ISSUE TITLE
NoMethodError for schemas resolved to nil

### ISSUE THREAD

**Issue by sriedel** [davishmcclurg/json_schemer#23]
I stubled across this chasing a bug in my code.
If you pass a proc/lambda with ref_resolver to the schemer, and this block resolves the passed uri to nil, it will cause an exception:

    NoMethodError: undefined method `empty?' for nil:NilClass
    /home/sr/.rvm/gems/ruby-2.6.0/gems/json_schemer-0.1.10/lib/json_schemer/schema/base.rb:79:in `validate_instance'

You'll probably want to raise an UnknownRef exception when the resolver returns something unuseable.

**Comment by davishmcclurg** [comment]
Addressed this in #26. Thanks!
