### ISSUE TITLE
undefined values in the json that have a default in the schema are replaced with the default before validation

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [davishmcclurg/json_schemer#29]
How I can replace undefined values in the json that have a default in the schema are replaced with the default before validation?

**Comment by davishmcclurg** [comment]
Unfortunately that feature isn't supported yet

**Comment by Serhiy-Nazarov** [comment]
is it planned?

**Comment by davishmcclurg** [comment]
I don't have a short-term plan to implement it, but if there's more interest I might try. Feel free to open a PR if you want to give it a shot.

**Comment by davishmcclurg** [comment]
@Serhiy-Nazarov does this look like it would solve your issue? https://github.com/davishmcclurg/json_schemer/pull/35

I'd prefer if it returned a new object instead of modifying the values in-place, but I think that would take a larger refactor.

**Comment by Serhiy-Nazarov** [comment]
Great thanks a lot!
