### ISSUE TITLE
regexp_parser dependency is old

### ISSUE THREAD

**Issue by kpmueller** [davishmcclurg/json_schemer#32]
The dependency on `regexp_parser` is old. For example, when running with capybara version 3 or later:

```
Bundler could not find compatible versions for gem "regexp_parser":
  In snapshot (Gemfile.lock):
    regexp_parser (= 1.5.1)

  In Gemfile:
    capybara (~> 3) was resolved to 3.25.0, which depends on
      regexp_parser (~> 1.5)

    json_schemer (~> 0.2.0) was resolved to 0.2.0, which depends on
      regexp_parser (~> 1.2.0)
```

is it possible to update the dependency, or make it not restricted to a minor version?

**Comment by davishmcclurg** [comment]
This should be fixed by: https://github.com/davishmcclurg/json_schemer/pull/31
Try 0.2.1

**Comment by kpmueller** [comment]
thanks much! @davishmcclurg
