### ISSUE TITLE
Type conversion

### ISSUE THREAD

**Issue by ahx** [davishmcclurg/json_schemer#49]
It would be very handy if json_schemer could also convert values. I was thinking about a new option like `conversion: true`, which could be false by default. If set to true and the data is valid, json_schemer could either modify the original data or return a new object.

There are not many things one would have to convert:
- { type: string, format: date  } -> Date
- { type: string, format: date-time  } -> DateTime
- { type: string, format: time  } -> Time
- { type: number  } -> Float

What do you think?

**Comment by davishmcclurg** [comment]
This feels a little out of scope, but seems useful. It looks like ajv has a `coerceTypes` option that does something slightly different: https://github.com/epoberezkin/ajv#coercing-data-types

I expect it would be hard to implement with the current code structure, unfortunately. Have you tried it?

**Comment by ahx** [comment]
I have not tried it, but, if the plan would be to modify the original data, maybe one could do something along the lines of ‚insert_property_defaults‘. Another approach could be to add some sort of hook somewhere, but have not looked into that. Maybe I can try to do something this Friday.

**Comment by ahx** [comment]
https://github.com/davishmcclurg/json_schemer/pull/77 mostly covers my use case for type conversion. There is an e[xample how to handle `format: 'date'`](https://github.com/davishmcclurg/json_schemer/blob/master/README.md#options) via the `after_property_validation` option in the README.
