### ISSUE TITLE
How to validate data against schema fragments?

### ISSUE THREAD

**Issue by mkon** [davishmcclurg/json_schemer#51]
Hi,

I am currently trying to replace json-schema gem with this gem. json-schema allowed validating data against a sub-schema specified by a fragment path, like this:

```ruby
schema = {
  "type"=>"object",
  "required" => ["a"],
  "properties" => {
    "a" => {
      "type" => "integer",
      "default" => 42
    },
    "b" => {
      "type" => "object",
      "properties" => {
        "x" => {
          "type" => "integer"
        }
      }
    }
  }
}

JSON::Validator.validate(schema, { "x" => 1 }, :fragment => "#/properties/b")
```

Is there anything similar possible here? Of course I could manually select the relevant part of schema and validate against that, however this would break references to any other parts of the schema. Especially in OpenApi3 schemas these references to other parts of the same json schema are very common.

I tried to manually create instances of `JSONSchemer::Schema::Base::Instance` with `data_pointer` and `schema_pointer` set but no real success.

**Comment by davishmcclurg** [comment]
Hm, this will be tricky with how things are currently working. You could potentially validate the entire schema and ignore errors that don't have the schema pointer as a prefix.

**Comment by ahx** [comment]
@mkon you could use a json pointer lib like [hana](https://rubygems.org/gems/hana):

```ruby
require 'hana'
require 'json_schemer'

schema = {
  "type"=>"object",
  "required" => ["a"],
  "properties" => {
    "a" => {
      "type" => "integer",
      "default" => 42
    },
    "b" => {
      "type" => "object",
      "properties" => {
        "x" => {
          "type" => "integer"
        }
      }
    }
  }
}
fragment = Hana::Pointer.new("/properties/b").eval(schema)
JSONSchemer.schema(fragment).valid?( { "x" => 1 }) # => true
```

**Comment by mkon** [comment]
Hey, thanks for your replies. Validating against a sub-part of the schema (like with hana) does not work in our case, as this would break links within the schema referencing other objects (think huge openapi schemas with hundreds of objects referencing each other).

Looking at the source code I think I found a solution that actually works now. We now inject the '$ref' key into the schema to point to the fragment we are interested:

```ruby
JSONSchemer.schema(schema.merge('$ref' => '/properties/b')).valid?( { "x" => 1 })
```

This makes your validator check against the subschema at `$ref`, while leaving all referenced objects intact.

**Comment by ahx** [comment]
@mkon Nice 💡.

**Comment by davishmcclurg** [comment]
@mkon very clever :+1:
