### ISSUE TITLE
Empty pointers returned from .validate with valid? returning false

### ISSUE THREAD

**Issue by walterbenson** [davishmcclurg/json_schemer#52]
I'm interested in adopting this gem but I'm having trouble getting started. Validation is clearly failing (valid? returns false) when I use this gem but passes when I use another. When I explore the result of validate I have empty pointers and data and schemas that look like they should match. Any suggestions?

**Comment by davishmcclurg** [comment]
Hi @walterbenson, sorry you're having issues. Can you share your schema and data so that I can debug it?
