### ISSUE TITLE
Wrong behavior of insert_property_defaults: true with oneOf

### ISSUE THREAD

**Issue by skryukov** [davishmcclurg/json_schemer#53]
`insert_property_defaults: true` causes validation failure when used with `'oneOf'`. In the following example `JSONSchemer` inserts `'a'` as a default for the `'bar'` key:

```ruby
require 'json_schemer'

schema = {
  'oneOf' => [
    { 
      'type' => 'object',
      'properties' => {
        'foo' => { 'enum' => ['a'] },
        'bar' => { 'enum' => ['a'], 'default' => 'a' }
      } 
    },
    {
      'type' => 'object',
      'properties' => {
        'foo' => { 'enum' => ['b'] },
        'bar' => { 'enum' => ['b'], 'default' => 'b' }
      } 
    },
  ]
}

schemer = JSONSchemer.schema(schema)

schemer.valid?('foo' => 'b')
# => true

schemer = JSONSchemer.schema(schema, insert_property_defaults: true)

schemer.valid?('foo' => 'b')
# => false
```

**Comment by davishmcclurg** [comment]
Interesting. What behavior are you expecting when using `insert_property_defaults` with `oneOf`? I can see a case for using the default from the valid subschema, but it's not totally clear to me.

**Comment by skryukov** [comment]
@davishmcclurg `oneOf` can be just a part of a schema that one want to populate with the defaults. I think it may be safer to not populate `oneOf`/ `allOf` / `anyOf` at all =)

**Comment by davishmcclurg** [comment]
Thanks @skryukov!
