### ISSUE TITLE
Support version-less $schema keyword

### ISSUE THREAD

**Issue by krystof-k** [davishmcclurg/json_schemer#63]
[Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/schema.html):
> It is recommended that all JSON Schemas have a $schema entry, which must be at the root. Therefore most of the time, you’ll want this at the root of your schema:
> ```json
> "$schema": "http://json-schema.org/schema#"
> ```

What do you think? We had to add a specific draft to our schemas.

**Comment by davishmcclurg** [comment]
It looks like `http://json-schema.org/schema#` redirects to the latest version (2019-09), which isn't supported yet:

```
% curl 'http://json-schema.org/schema#'
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="/draft/2019-09/schema">
  <meta http-equiv="refresh" content="0; url=/draft/2019-09/schema">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <p>
    Several redirections on json-schema.org are special cases:
  </p>
  <ul>
    <li>The unversioned meta-schema URIs should no longer be used.</li>
    <li>The vocabularies are represented by their specification text.</li>
    <li>The "latest" specification URIs are for convenice of browser
        bookmarking only.</li>
  </ul>
  <a href="/draft/2019-09/schema">Click here if you are not redirected.</a>
  <script>location="/draft/2019-09/schema"</script>
</html>
```

It also says:

> The unversioned meta-schema URIs should no longer be used.

---

Which draft did you intend to use? You shouldn't need to specify `$schema` if you're using the current default meta schema, which is 7:

https://github.com/davishmcclurg/json_schemer/blob/6bc8f60c9b48258828d51d65fc65adf0701eba0e/lib/json_schemer.rb#L36

**Comment by krystof-k** [comment]
You are right (see json-schema-org/json-schema-spec#216). In this case, what about to map it to the draft 4?

**Comment by davishmcclurg** [comment]
Unless there's a good reason not to, I'd rather leave the default as the latest supported version.

**Comment by krystof-k** [comment]
I don't mean to change the default, but to add a new mapping, something like this:

```ruby
DRAFT_CLASS_BY_META_SCHEMA = {
    'http://json-schema.org/schema#' => Schema::Draft4,
    'http://json-schema.org/draft-04/schema#' => Schema::Draft4,
    …
  }.freeze
```

**Comment by davishmcclurg** [comment]
That doesn't seem quite right since http://json-schema.org/schema# still redirects to http://json-schema.org/draft/2019-09/schema

But I'm open to the change if it's true that http://json-schema.org/schema# was deprecated before later drafts were published.

**Comment by krystof-k** [comment]
Good point.

Well, yes, in Draft 5, there is no mention of the version-less URI whereas in [Draft 4](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-6):

> 6.  The "$schema" keyword
>  …
> 
> The following values are predefined:
> 
> http://json-schema.org/schema#  JSON Schema written against the
>     current version of the specification.

**Comment by davishmcclurg** [comment]
Sounds good to me. Feel free to open a PR with the change. Otherwise I'll get to it at some point.
