### ISSUE TITLE
Date validation misses some invalid values

### ISSUE THREAD

**Issue by ashleyyy** [davishmcclurg/json_schemer#72]
The DateTime.rfc3339 used [here](herehttps://github.com/davishmcclurg/json_schemer/blob/8c9b56515b1e9f834438a3cd44dfb9d32c5812d4/lib/json_schemer/format.rb#L61) to check for valid dates doesn't raise an error when the year has more than four digits or starts with a `-`. 

Technically `-0001-12-31` is a real date but it breaks our BigQuery implication.

**Comment by davishmcclurg** [comment]
Can you provide some examples of what you're expecting? Using the `date` format, I'm seeing 5 digit years as invalid and `-0001-12-31` as valid:

```
>> schemer = JSONSchemer.schema({ 'format' => 'date' })
=> #<JSONSchemer::Schema::Draft7:0x00007fa043182ac8 @root={"format"=>"date"}, @format=true, @insert_property_defaults=false, @formats=nil, @keywords=nil, @ref_resolver=#<Proc:0x00007fa0439e8230@/Users/dharsha/repos/json_schemer/lib/json_schemer/schema/base.rb:21>>
>> schemer.valid?('-0001-12-31')
=> true
>> schemer.valid?('10000-12-31')
=> false
```

**Comment by ashleyyy** [comment]
Oh it looks like I was a version behind, when I update I do see what you're seeing for the 5 digit years but I am still getting invalid `-0001-12-31`. I don't really think that a negative year should be considered valid, do you?

**Comment by davishmcclurg** [comment]
> I don't really think that a negative year should be considered valid, do you?

Hm, a negative year seems ok to me, but it's not totally clear from reading about [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Years):

> To represent years before 0000 or after 9999, the standard also permits the expansion of the year representation but only by prior agreement between the sender and the receiver.

It says basically the same thing about any year before 1583:

> Instead "values in the range [0000] through [1582] shall only be used by mutual agreement of the partners in information interchange."

I feel ok about leaving it up to Ruby's implementation of `DateTime.rfc3339`. As a workaround, you could define a custom format: https://github.com/davishmcclurg/json_schemer/blob/ec9b051104aa063ea3f0ac913999f256556ad5dd/lib/json_schemer/schema/base.rb#L36
