### ISSUE TITLE
Remove Ruby version constraint from the gemspec

### ISSUE THREAD

**Issue by Marahin** [davishmcclurg/json_schemer#76]
Hello,

we would love to use this gem to validate JSON payloads on-failure in our gem, [jsonapi_parameters](https://github.com/visualitypl/jsonapi_parameters). This gem provides a simple way to consume JSON:API compliant inputs in Ruby, with Rails support included. You can read more about the standard here: https://jsonapi.org

Sadly, we are facing an issue where choosing json_schemer as the validation engine would mean that we would have to give up support for Ruby 2.4. While we are aware that this Ruby version has reached its EOL, we would rather not limit our users to specific Ruby versions unless it is required by the gem's logic.

Because of that we are currently seeing three scenarios:
* either exporting the validation as a plug-in (so the validation part would be excluded out of JsonApi::Parameters gem and instead be provided as a complementary gem),
* leave it as it is in the current state (PR link: https://github.com/visualitypl/jsonapi_parameters/pull/45), thus give up for Ruby versions below 2.5.0,

and, the third scenario is: reaching out and asking whether its possible (and if not - what is the reason for this decision) to **remove the constraint in json_schemer** that enforces Ruby versions above 2.4.0. This is the path that we decided to choose first. 

Commit link: https://github.com/davishmcclurg/json_schemer/commit/8cbd5ccf4ce4eaa11d75ffa1518340fc6b437e52#diff-6f69d521c8f547072ea493be84d7a52eL23-R23

**Comment by ahx** [comment]
IMHO with Ruby 3 just a few months to go, let’s nudge people towards using  newer Ruby versions. 🚀

**Comment by Marahin** [comment]
> IMHO with Ruby 3 just a few months to go, let’s nudge people towards using newer Ruby versions.


Why? Why forcing people to update their well-working scripts, gems, programs would be the way to go?
Ruby is an open-minded community, and while Ruby 3 is great, I do not share an opinion of forcing anybody to upgrade their Ruby version solely because there's a newer one.

Ruby version requirement should be dictated by the need of the language functionalities, not because of language creators' support. 
**New applications should indeed be written in the highest Ruby versions possible**, but please allow users that already have their use-cases covered to have their application still working without having to upgrade _everything_ just so they can validate their JSON inputs.

**Comment by ahx** [comment]
@Marahin Alright. Sounds plausible.

**Comment by davishmcclurg** [comment]
> we would love to use this gem to validate JSON payloads on-failure in our gem, [jsonapi_parameters](https://github.com/visualitypl/jsonapi_parameters).

Sounds great!

> and, the third scenario is: reaching out and asking whether its possible (and if not - what is the reason for this decision) to **remove the constraint in json_schemer** that enforces Ruby versions above 2.4.0. This is the path that we decided to choose first.

I originally enforced Ruby 2.5 because 2.4 is EOL and I'd like to use some of the features in 2.5. Would it work for you to pin your dependency on an older version of the gem? I believe 0.2.11 works on Ruby 2.4. In fact, bundler should pick up that version when running on 2.4.

**Comment by Marahin** [comment]
@davishmcclurg  indeed we could pin down to the version before the Ruby 2.5 dependency was introduced, but this way we are giving up on the new features, fixes and changes in your library, such as more precise errors: https://github.com/davishmcclurg/json_schemer/issues/1

So while this would indeed allow us to include and use json_schemer, it:
* creates another issue (what about new features? We are locking ourselves to one specific version),
* already by the time its introduced will be outdated

>I'd like to use some of the features in 2.5

This is a super valid point, but are there any features that json_schemer is making use of right now? If yes, then this indeed discards our request and is a great argument behind setting this dependency up.

**Comment by davishmcclurg** [comment]
> This is a super valid point, but are there any features that json_schemer is making use of right now?

I think you're right that there aren't any. I was thinking of some things I changed when I dropped 2.3.

> but this way we are giving up on the new features, fixes and changes in your library, such as more precise errors: #1

That's true. I'm open to supporting 2.4 again since it shouldn't require any other changes. How long do you plan to support it? I don't have a good sense for people's expectations on these types of things.

Please open a PR with the changes, if you can.

**Comment by davishmcclurg** [comment]
Merged 2.4 support and released in 0.2.14.
