### ISSUE TITLE
Invalid schema is silently accepted

### ISSUE THREAD

**Issue by mwsteb** [davishmcclurg/json_schemer#80]
I'm using `json_schemer (0.2.11)` in the project and couldn't help but notice some unexpected behaviour.

Is it expected that no errors are being raised when an invalid schema is provided to the `.schema` method?

I noticed it when I was debugging a schema that looked correct at a glance, but proved invalid upon closer inspection:

```
{
      "type" => "object",
      "properties" => {
        "type" => "array",
        "items" => {
          "type" => "object",
          "properties" => {...some properties...}
        }
      }
    }
```

The above is invalid, because the nested array value has no property name that would act as a key for the object type.

I digged a little deeper, and it seems like JSONSchemer doesn't care about schema validity at all.
For instance:

```
[5] pry> JSONSchemer.schema("potato cheese pierogi" => "Margaret Thatcher").valid?({ "some" => "json data" })
=> true
```

For contrast, [an online json schema validator I found](https://json-schema-validator.herokuapp.com/) offers a following error in such a case:
```
[ {
  "level" : "fatal",
  "message" : "invalid JSON Schema, cannot continue\nSyntax errors:\n[ {\n  \"level\" : \"error\",\n  \"schema\" : {\n    \"loadingURI\" : \"#\",\n    \"pointer\" : \"/properties/type\"\n  },\n  \"domain\" : \"syntax\",\n  \"message\" : \"JSON value is of type string, not a JSON Schema (expected an object)\",\n  \"found\" : \"string\"\n} ]",
  "info" : "other messages follow (if any)"
}, {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/properties/type"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
} ]
```

Would it make more sense to raise a similar error in the described case? Either on `.schema` call or on `#valid?` call?

**Comment by davishmcclurg** [comment]
> Is it expected that no errors are being raised when an invalid schema is provided to the `.schema` method?

That is expected (to me at least :)). I initially wrote JSONSchemer because `json-schema` was surprisingly slow (and didn't support draft 7), so I wanted to avoid the extra work of validating the schema itself. I do think people would find it useful to offer schema validation, though.

> Would it make more sense to raise a similar error in the described case? Either on `.schema` call or on `#valid?` call?

I'd probably add that as a separate method, something like `JSONSchemer.schema(schema).valid_schema?` or `JSONSchemer.valid_schema?(schema)`. That way people that know their schemas are valid don't have to deal with the overhead.

**Comment by mwsteb** [comment]
> That is expected (to me at least :)). I initially wrote JSONSchemer because json-schema was surprisingly slow (and didn't support draft 7), so I wanted to avoid the extra work of validating the schema itself. I do think people would find it useful to offer schema validation, though.

I see.

Agreed, I reckon it makes sense to make it an opt-in behaviour then. I'll try too cook something up.

**Comment by mkwu** [comment]
any updates on this?  Would love to have this as an option!

**Comment by davishmcclurg** [comment]
> any updates on this? Would love to have this as an option!

No updates on my end. I don't think a `valid_schema?` implementation would be too complicated, if anyone feels like contributing. I believe we could ship the meta-schemas (eg, [draft 7](https://json-schema.org/draft-07/schema)) and run a regular validation. Could also cover https://github.com/davishmcclurg/json_schemer/issues/41.

**Comment by davishmcclurg** [comment]
v1.0.0 added support for validating schemas:

```ruby
JSONSchemer.valid_schema?(schema)
JSONSchemer.validate_schema(schema)
JSONSchemer.schema(schema).valid_schema?
JSONSchemer.schema(schema).validate_schema
```

These work the same way as the data validation methods: `valid?` (returns boolean) and `validate` (returns error enumerator).
