### ISSUE TITLE
Strict validation

### ISSUE THREAD

**Issue by tyler-wel** [davishmcclurg/json_schemer#82]
# Issue/Question

Trying to migrate from [ruby-json-schema](https://github.com/ruby-json-schema/json-schema), I realized `json_schemer` doesn't seem to have a `:strict` validation option.

Given
```json
{
  "type": "object", 
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

Using `ruby-json-schema`
```ruby
::JSON::Validator.validate(schema, {"name" => "test", "extra_col" => 1}, :strict => true )
=> false

::JSON::Validator.fully_validate(schema, {"name" => "test", "extra_col" => 1}, :strict => true )
=> ["The property '#/' contained undefined properties: 'extra_col' in schema ca942ccb-0676-5741-b04d-40ca0787af04"]
```

The strict validation fails because of the extra column. 

Is there anyway currently to achieve this with `json_schemer`?

**Comment by davishmcclurg** [comment]
You can get the same behavior using `additionalProperties` and `required`:

```json
{
  "type": "object", 
  "additionalProperties": false,
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

It looks like `strict` isn't part of the JSON schema spec—probably a feature specific to ruby-json-schema.

**Comment by tyler-wel** [comment]
Thank you for the information 😄
