### ISSUE TITLE
Allow for regexp_parser 2.x

### ISSUE THREAD

**Issue by tas50** [davishmcclurg/json_schemer#85]
Hi there,

The regexp_parser project has released the 2.0 version, which RuboCop now depends on. The conflicts with the 1.x release supported in this gem and results in nasty conflicts for anyone that tries to link their Ruby code. It would be wonderful if a release could be cut supporting the 2.x regexp_parser release.

**Comment by ggrocco** [comment]
This is linked to my PR #86

**Comment by davishmcclurg** [comment]
0.2.17 should work with regexp_parser 2.0
