### ISSUE TITLE
Add support for symbolized keys

### ISSUE THREAD

**Issue by mbykovskyy** [davishmcclurg/json_schemer#91]
Currently, parsed JSON with symbolized key fails validation. Please add support for validating JSON with symbolized keys.

**Comment by AhmedKamal20** [comment]
> Have you got an example for what this trips up on? @jamietanna 

Passing a schema with symbolized keys like this :
`validates :data, presence: false, json: { message: ->(errors) { errors }, schema: { type: :object } }`
Raise this error :
`JSONSchemer::InvalidSymbolKey (schemas must use string keys)`

But like this
`validates :data, presence: false, json: { message: ->(errors) { errors }, schema: { "type" => :object } }`
Works fine

**Comment by davishmcclurg** [comment]
Released in 2.0.0. Schema keys are deep-stringified to support symbols.

Note: symbol values are not supported (eg, `type: :object` above).
