### ISSUE TITLE
Add CLI support

### ISSUE THREAD

**Issue by joaopfernandesc** [davishmcclurg/json_schemer#95]
First of all, thank you for building this gem! I've been using it a lot.

I'm working with multiple JSON Schemas and its correspondent examples. In my opinion, it would be really great to add CLI support to validate payloads.

If you think this is a reasonable feature request, let me know and I can work on a PR.

**Comment by davishmcclurg** [comment]
Hey @joaopfernandesc—sounds good to me! Let me know if I can help. I'm thinking something simple like this?

```
bin/json_schemer --schema /path/to/schema.json /path/to/data.json
```
