### ISSUE TITLE
Bug: `anyOf` and `oneOf` handle the absence of `type` on subschemas differently

### ISSUE THREAD

**Issue by myronmarston** [davishmcclurg/json_schemer#96]
My understanding of `anyOf` and `oneOf` is that they behave identically except that `anyOf` allows _more_ than one subschema to match, where as `oneOf` requires _exactly one_ of the subschemas to match.  However, I'm seeing a case where `json_schemer` implements additional differing (and puzzling behavior) between the two.

Here's a script that reproduces the issue:

``` ruby
require 'bundler/inline'
puts "RUBY_VERSION: #{RUBY_VERSION}"

gemfile  do
  source 'https://rubygems.org'
  gem 'json_schemer'
end

require "json_schemer"

def validator_with(keyword)
  schema = {
    keyword => [
      {
        "type" => ("object" if ENV["INCLUDE_TYPE"]),
        "properties" => {
          "foo" => {"type" => "string"},
        },
        "required" => ["foo"]
      }.compact,
      {
        "type" => ("object" if ENV["INCLUDE_TYPE"]),
        "properties" => {
          "bar" => {"type" => "string"},
        },
        "required" => ["bar"]
      }.compact,
      {"type" => "null"}
    ]
  }

  JSONSchemer.schema(schema)
end

any_of_validator = validator_with("anyOf")
one_of_validator = validator_with("oneOf")

[
  {"foo" => "abc"},
  {"bar" => "abc"},
  {"baz" => "abc"},
  nil
].each do |document|
  puts "-" * 80

  any_of_errors = any_of_validator.validate(document).to_a
  one_of_errors = one_of_validator.validate(document).to_a

  if any_of_errors.empty? && one_of_errors.empty?
    puts "#{document.inspect}: valid against both validators"
  elsif any_of_errors.any? && one_of_errors.any?
    puts "#{document.inspect}: invalid against both validators"
  else
    puts "#{document.inspect}: differing validity: "
    puts "anyOf errors: #{any_of_errors.inspect}"
    puts "oneOf errors: #{one_of_errors.inspect}"
  end
end
```

Here's the output when I run it:

```
$ ruby script/json_schemer_one_of.rb
RUBY_VERSION: 2.7.1
--------------------------------------------------------------------------------
{"foo"=>"abc"}: valid against both validators
--------------------------------------------------------------------------------
{"bar"=>"abc"}: valid against both validators
--------------------------------------------------------------------------------
{"baz"=>"abc"}: invalid against both validators
--------------------------------------------------------------------------------
nil: differing validity:
anyOf errors: []
oneOf errors: [{"data"=>nil, "data_pointer"=>"", "schema"=>{"oneOf"=>[{"properties"=>{"foo"=>{"type"=>"string"}}, "required"=>["foo"]}, {"properties"=>{"bar"=>{"type"=>"string"}}, "required"=>["bar"]}, {"type"=>"null"}]}, "schema_pointer"=>"", "root_schema"=>{"oneOf"=>[{"properties"=>{"foo"=>{"type"=>"string"}}, "required"=>["foo"]}, {"properties"=>{"bar"=>{"type"=>"string"}}, "required"=>["bar"]}, {"type"=>"null"}]}, "type"=>"oneOf"}]
```

As you can see, `{"foo" => "abc"}` and `{"bar" => "abc"}` are both correctly valid against the `oneOf` and `anyOf` schemas. `{"baz" => "abc"}` is correctly invalid against both schemas.

But `nil` is treated differently here: on the `anyOf` schema, it's considered valid but on the `oneOf` schema it's considered invalid.  However, `nil` should not match multiple of the subschemas on either the `anyOf` or the `oneOf` schemas...so it's not clear to me why `anyOf` and `oneOf` behave differently here.

It appears to have to do with the fact that the non-null subschemas lack `"type" => "object"`.  If you add them (which the script supports via an `INCLUDE_TYPE` env var), then `anyOf` and `oneOf` behave the same here:

```
$ INCLUDE_TYPE=1 ruby script/json_schemer_one_of.rb
RUBY_VERSION: 2.7.1
--------------------------------------------------------------------------------
{"foo"=>"abc"}: valid against both validators
--------------------------------------------------------------------------------
{"bar"=>"abc"}: valid against both validators
--------------------------------------------------------------------------------
{"baz"=>"abc"}: invalid against both validators
--------------------------------------------------------------------------------
nil: valid against both validators
```

`nil` is valid against both schemas in this case.

**Comment by davishmcclurg** [comment]
Thanks for the report @myronmarston! I think the problem you're running into is that `nil` is valid for all of your schemas when you don't specify `type`:

```
?> JSONSchemer.schema({
?>   'properties' => {
?>     'foo' => {
?>       'const' => 'valid'
?>     }
?>   }
>> }).valid?(nil)
=> true
```

I believe ignoring `properties` like this is expected behavior as noted in the [spec](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-3.2.1):

> Most validation assertions only constrain values within a certain
> primitive type.  When the type of the instance is not of the type
> targeted by the keyword, the instance is considered to conform to the
> assertion.
> 
> For example, the "maxLength" keyword will only restrict certain
> strings (that are too long) from being valid.  If the instance is a
> number, boolean, null, array, or object, then it is valid against
> this assertion.

The type of the instance in this case is `nil`, which is not targeted by the `properties` keyword. You'll need to provide a `type` to restrict the type.

**Comment by myronmarston** [comment]
Thanks @davishmcclurg, that makes sense but is certainly a subtlety in the behavior!

**Comment by davishmcclurg** [comment]
> Thanks @davishmcclurg, that makes sense but is certainly a subtlety in the behavior!

Definitely confused me at first. I think the safest thing to do is always specify `type`.
